#!/usr/bin/env python3
"""Build the standalone mobile Beat Slicer HTML with all bundled MP3 files embedded."""

from __future__ import annotations

import argparse
import base64
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / "mobile" / "beat_slicer_mobile.source.html"
DEFAULT_OUTPUT = ROOT / "beat_slicer_mobile.html"
TRACKS = (
    "Free_Flow_Flava_-_Mistake_79894259.mp3",
    "QMIIR_-_YALA_Slowed_81306825.mp3",
    "Ian_Asher_-_Take_Me_To_The_Moon_81645636.mp3",
    "Rammstein_Andrea_Marino_-_Adieu_-_RMX_by_Andrea_Marino_76187476.mp3",
)


def embed_track(html: str, filename: str) -> str:
    path = ROOT / filename
    if not path.is_file():
        raise SystemExit(f"missing bundled track: {path}")
    marker = f'src="{filename}"'
    if html.count(marker) != 1:
        raise SystemExit(f"expected exactly one {marker!r} in mobile source")
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return html.replace(marker, f'src="data:audio/mpeg;base64,{encoded}"')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    html = args.source.read_text(encoding="utf-8")
    for filename in TRACKS:
        html = embed_track(html, filename)
    banner = "<!-- GENERATED by tools/build_mobile.py; edit mobile/beat_slicer_mobile.source.html -->\n"
    args.output.write_text(banner + html, encoding="utf-8")
    print(f"wrote {args.output} ({args.output.stat().st_size / 1024 / 1024:.2f} MiB)")


if __name__ == "__main__":
    main()
